-----------------   Section A – Conceptual Understanding  -----------------


A1. Why are NumPy arrays preferred over Python lists?
NumPy arrays are generally faster than normal Python lists when we work with numerical data. They also use memory more efficiently because the elements in an array usually have the same data type. NumPy provides useful mathematical operations such as mean, standard deviation, matrix multiplication, and aggregation directly on arrays. 


A2. What is vectorization?

Vectorization means performing an operation on an entire NumPy array at once instead of processing each element using a Python for loop. For example, we can multiply an entire array by 2 using arr * 2. This is important for large datasets because NumPy's optimized operations are usually much faster than running Python loops element by element.



A3. Difference between A * B and A @ B

A * B performs element-wise multiplication, meaning corresponding elements of the two arrays are multiplied Where, A @ B performs matrix multiplication, where rows of one matrix are multiplied with columns of another matrix. 

A4. What is broadcasting?

Broadcasting is a NumPy feature that allows arrays with different but compatible shapes to be used together in element-wise operations. NumPy compares their dimensions from right to left. Two dimensions are compatible when they are equal, or when one of them is 1; missing dimensions are also treated as 1. This allows operations such as adding a single value or a row/column vector to a larger array.

A5. flatten() vs ravel()

Both flatten() and ravel() convert an array into a one-dimensional array. The main difference is that flatten() always creates a copy, while ravel() tries to return a view of the original array whenever possible. In a memory-constrained application processing large images, I would prefer ravel() because it can avoid creating an unnecessary copy and therefore save memory.

A6. Explain axis=0 and axis=1
For a 2D array, axis=0 means the operation is performed down the rows, so we get a result for each column. axis=1 means the operation is performed across the columns, so we get a result for each row.

In [1]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


A7. Normalization vs Standardization

Normalization and standardization are used to bring numerical features into a suitable range or scale before training an ML model. Normalization usually changes values to a fixed range, commonly [0, 1], using the minimum and maximum values. Standardization changes values so that the mean becomes approximately 0 and the standard deviation becomes 1. Scaling is especially useful for models where features with larger numerical values could otherwise dominate smaller-valued features.

A8. Why does np.nanmean() exist?

np.nanmean() is useful when our data contains NaN values and we want to calculate the mean while ignoring those missing values. If we use np.mean() directly on an array containing NaN, the result will normally become NaN. Therefore, np.nanmean() is useful when missing values are present and we want the mean of the available values.

A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128. 

In ML, X.shape = (samples, features) means that the first dimension represents the number of samples. For RGB images, we normally have dimensions representing the number of images, height, width, and color channels.
For 64 RGB images of size 128 × 128, the shape is: (64, 128, 128, 3)
Here, 64 is the number of images, 128 × 128 is the image size, and 3 represents the RGB channels.

A10. Why is reproducibility important?

Reproducibility means getting the same results when an experiment is repeated under the same conditions. Random operations can produce different results each time, which makes it difficult to compare experiments.

-----------------  Section B – Predict the Output  ------------------

B1. Predict the exact output and/or resulting shape. Justify in one      sentence.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

# a has shape (3,) and b has shape (3,1). NumPy broadcasts them to a 3 × 3 array before addition.


(3, 3)


B2. Predict the output and/or shape.

In [ ]:
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])
# It selects the second column from both rows.

[2 5]


B3. Predict the output and/or shape.

In [6]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

#Only 10 and 20 have a remainder of 0 when divided by 10.

[10 20]


B4. Predict the output and/or shape.

In [ ]:
m = np.array([[1, 2],[3, 4]])
print(m.T @ m)

# m.T transposes the matrix and @ performs matrix multiplication.

[[10 14]
 [14 20]]


B5. Predict the output and/or shape.

In [9]:
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

# np.mean() returns nan because the array contains NaN, while np.nanmean() ignores the NaN value and calculates the mean of 1, 2, 4.

nan 2.3333333333333335


B6. Predict the output and/or shape.

In [10]:
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

#  np.where() gives 1 when the condition is true and 0 when it is false.

[0 1 1]


B7. Predict the output and/or shape.

In [ ]:
a = np.zeros((3, 4))
print(a.ndim, a.size)

#  ndim gives the number of dimensions, which is 2, and size gives the total number of elements, which is 12.

2 12


B8. Predict the output and/or shape.

In [13]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

#  Both the rows and columns are reversed using [::-1, ::-1]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


------------------ Section C – Coding / Implementation  -------------------

C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

In [ ]:
import numpy as np
scores = np.array([35, 45, 67, 28, 90, 39])
result = np.where(scores >= 40, 'P', 'F')
print(result)

#np.where() checks each score and gives P if the score is 40 or above; otherwise it gives F.

['F' 'P' 'P' 'F' 'P' 'F']


C2.Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

In [ ]:
import numpy as np
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std
x = np.array([10, 20, 30, 40, 50])
result = standardize(x)
print(result)

# The z-score is calculated using (x - mean) / standard deviation, which centers the data around 0.

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


C3. The z-score is calculated using (x - mean) / standard deviation, which centers the data around 0.

In [17]:
import numpy as np
batch1 = np.array([[1, 2, 3],[4, 5, 6]])
batch2 = np.array([[7, 8, 9],[10, 11, 12]])
combined = np.vstack((batch1, batch2))
print(combined)
print("Shape:", combined.shape)

# np.vstack() joins the two batches row-wise because both arrays have the same number of features.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)


C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

In [24]:
import numpy as np
X = np.random.default_rng(42).normal(size=(100, 5))
mean = X.mean(axis=0)
std = X.std(axis=0)
X_standardized = (X - mean) / std
print("Shape:", X_standardized.shape)

# axis=0 calculates the mean and standard deviation separately for each of the 5 feature columns.

Shape: (100, 5)


C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true. 

In [ ]:
import numpy as np
X = np.array([[1, 2],[2, 3],[3, 4]])
w = np.array([0.5, 1.0])
b = 2.0
y_true = np.array([4, 6, 8])
y_pred = X @ w + b
mse = np.mean((y_true - y_pred) ** 2)
print("Predicted:", y_pred)
print("MSE:", mse)

#  X @ w + b calculates the predictions, and MSE calculates the average squared difference between actual and predicted values.

Predicted: [4.5 6.  7.5]
MSE: 0.16666666666666666


C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. 

In [21]:
import numpy as np
rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))
rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))
print("Shape:", data1.shape)
print("Identical results:", np.array_equal(data1, data2))

# Using the same random seed generates the same random values, so both arrays are identical.

Shape: (10, 3)
Identical results: True


C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.

In [ ]:
import numpy as np
image = np.array([[0, 50, 100],[150, 200, 255]])
normalized = (image - image.min()) / (image.max() - image.min())
print(normalized)

# Min-max normalization converts the minimum pixel value to 0 and the maximum pixel value to 1, with the other values scaled between them.

C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why. 

In [22]:
import numpy as np
images = np.random.default_rng(42).integers(0, 256, size=(4, 28, 28, 3))
average = images.mean(axis=(1, 2, 3))
print("Average pixel values:", average)
print("Shape:", average.shape)

# Here, we keep axis=0 which represent the images. we get one average value for each image.

Average pixel values: [127.56505102 126.25212585 125.75722789 126.9914966 ]
Shape: (4,)


-------------- Section D – Applied / Scenario-BasedProblems ---------------

D1.Data Preprocessing Pipeline 
You are given a raw 1D or 2D NumPy array containing NaN values.
Describe, step by step, the NumPy operations you would apply to:
(a) detect missing values,
(b) handle them appropriately and justify your strategy, and
(c) normalize or standardize the clean data before it is fed to a model.


In [ ]:
import numpy as np
data = np.array([[10.0, 100.0],[20.0, np.nan],[30.0, 300.0],[np.nan, 400.0]])

missing = np.isnan(data)
print("Missing values:")
print(missing)

column_mean = np.nanmean(data, axis=0)

# Replaced NaN values with column mean
clean_data = np.where(missing, column_mean, data)
print("\nClean data:")
print(clean_data)

mean = clean_data.mean(axis=0)
std = clean_data.std(axis=0)
standardized = (clean_data - mean) / std
print("\nStandardized data:")
print(standardized)

# np.isnan() detects missing values, np.nanmean() helps calculate replacement values while ignoring NaN, and the cleaned data is standardized using mean and standard deviation.

Missing values:
[[False False]
 [False  True]
 [False False]
 [ True False]]

Clean data:
[[ 10.         100.        ]
 [ 20.         266.66666667]
 [ 30.         300.        ]
 [ 20.         400.        ]]

Standardized data:
[[-1.41421356 -1.5430335 ]
 [ 0.          0.        ]
 [ 1.41421356  0.3086067 ]
 [ 0.          1.2344268 ]]


D2. Image Batch Understanding 

Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

Compute the average image of the batch, meaning the element-wise mean across all 16 images.

State the shape of your result and explain why.

In [ ]:
import numpy as np
rng = np.random.default_rng(42)
images = rng.integers(0, 256,size=(16, 64, 64, 3))
print("Batch shape:", images.shape)

average_image = images.mean(axis=0)
print("Average image shape:", average_image.shape)

# A batch has shape (16, 64, 64, 3), and averaging along axis=0 removes the batch dimension and produces one average RGB image with shape (64, 64, 3).

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


D3. Debug the Model Code 
The following code contains more than one bug:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)
w = np.array([0.5, 1.0, 0.2])  # intended weight vector
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean(y_true - y_pred ** 2)
Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.

In [ ]:
import numpy as np
X = np.array([[1, 2],[2, 3],[3, 4]])
w = np.array([0.5, 1.0])
b = 2.0
y_pred= X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean((y_true - y_pred) ** 2)
print("Predicted values:", y_pred)
print("MSE:", mse)

# The weight vector must match the number of features in X, and parentheses are needed in the MSE formula so that the prediction error is squared before taking its mean

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


--------------------- Section E – Bonus / Challenge ------------------------

E1. Per-Column Min–Max Normalization [5 marks]
Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

In [ ]:
import numpy as np
X = np.array([[10, 100],[20, 200],[30, 300],[40, 400]])
column_min = X.min(axis=0)
column_max = X.max(axis=0)
normalized = (X - column_min) / (column_max - column_min)
print("Normalized data:")
print(normalized)

# axis=0 calculates the minimum and maximum separately for each feature column, and broadcasting applies the normalization without using loops.

E2. Three-Level Score Classification [5 marks]
Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).

Hint: You may need to nest or combine np.where() calls.

In [29]:
import numpy as np
scores = np.array([25, 40, 55, 70, 71, 90])
result = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent"))
print(result)

# The first np.where() identifies scores below 40 as Fail, and the nested np.where() classifies the remaining scores as Average or Excellent.

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']
